### ISSUE TITLE
load_results does not work for 2025

### ISSUE THREAD

**Issue by appiehappie999** [SCasanova/f1dataR#277]
**load_results(season = "current", round = "last")**
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `AverageSpeed` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `AverageSpeed` doesn't exist.
---
Backtrace:
     ▆
  1. ├─f1dataR::load_results(season = "current", round = "last")
  2. │ ├─base::withVisible(eval(mc, parent.frame()))
  3. │ └─base::eval(mc, parent.frame())
  4. │   └─base::eval(mc, parent.frame())
  5. ├─f1dataR (local) `<fn>`(season = "current", round = "last")
  6. │ └─... %>% janitor::clean_names()
  7. ├─janitor::clean_names(.)
  8. ├─tibble::as_tibble(.)
  9. ├─dplyr::mutate(., time_sec = time_to_sec(.data$fastest))
 10. ├─dplyr::select(...)
 11. ├─base::suppressMessages(.)
 12. │ └─base::withCallingHandlers(...)
 13. ├─base::suppressWarnings(.)
 14. │ └─base::withCallingHandlers(...)
 15. ├─tidyr::unnest(., cols = c("Time", "AverageSpeed"), names_repair = "universal")
 16. ├─dplyr::select(...)
 17. └─dplyr:::select.data.frame(...)
Run rlang::last_trace(drop = FALSE) to see 19 hidden frames.
> rlang::last_trace(drop = FALSE)
<error/vctrs_error_subscript_oob>
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `AverageSpeed` doesn't exist.
---
Backtrace:
     ▆
  1. ├─f1dataR::load_results(season = "current", round = "last")
  2. │ ├─base::withVisible(eval(mc, parent.frame()))
  3. │ └─base::eval(mc, parent.frame())
  4. │   └─base::eval(mc, parent.frame())
  5. ├─f1dataR (local) `<fn>`(season = "current", round = "last")
  6. │ └─... %>% janitor::clean_names()
  7. ├─janitor::clean_names(.)
  8. ├─tibble::as_tibble(.)
  9. ├─dplyr::mutate(., time_sec = time_to_sec(.data$fastest))
 10. ├─dplyr::select(...)
 11. ├─base::suppressMessages(.)
 12. │ └─base::withCallingHandlers(...)
 13. ├─base::suppressWarnings(.)
 14. │ └─base::withCallingHandlers(...)
 15. ├─tidyr::unnest(., cols = c("Time", "AverageSpeed"), names_repair = "universal")
 16. ├─dplyr::select(...)
 17. ├─dplyr:::select.data.frame(...)
 18. │ └─tidyselect::eval_select(expr(c(...)), data = .data, error_call = error_call)
 19. │   └─tidyselect:::eval_select_impl(...)
 20. │     ├─tidyselect:::with_subscript_errors(...)
 21. │     │ └─base::withCallingHandlers(...)
 22. │     └─tidyselect:::vars_select_eval(...)
 23. │       └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 24. │         └─tidyselect:::eval_c(expr, data_mask, context_mask)
 25. │           └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 26. │             └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 27. │               └─tidyselect:::eval_colon(expr, data_mask, context_mask)
 28. │                 └─tidyselect:::walk_data_tree(...)
 29. │                   └─tidyselect:::as_indices_sel_impl(...)
 30. │                     └─tidyselect:::as_indices_impl(...)
 31. │                       └─tidyselect:::chr_as_locations(x, vars, call = call, arg = arg)
 32. │                         └─vctrs::vec_as_location(...)
 33. └─vctrs (local) `<fn>`()
 34.   └─vctrs:::stop_subscript_oob(...)
 35.     └─vctrs:::stop_subscript(...)
 36.       └─rlang::abort(...)

sessionInfo()
R version 4.4.3 (2025-02-28)
Platform: aarch64-apple-darwin24.2.0
Running under: macOS Sequoia 15.3.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /opt/homebrew/Cellar/r/4.4.3/lib/R/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Amsterdam
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] logger_0.4.0        f1dataR_2.0.0       reticulate_1.41.0.1 stringi_1.8.4       tabulapdf_1.0.5-5  
 [6] yaml_2.3.10         RMySQL_0.11.0       dplyr_1.1.4         stringr_1.5.1       duckdb_1.2.1       
[11] DBI_1.2.3          

loaded via a namespace (and not attached):
 [1] rappdirs_0.3.3    utf8_1.2.4        generics_0.1.3    tidyr_1.3.1       lattice_0.22-6   
 [6] digest_0.6.37     hms_1.1.3         magrittr_2.0.3    grid_4.4.3        timechange_0.3.0 
[11] pkgload_1.4.0     fastmap_1.2.0     jsonlite_1.9.1    Matrix_1.7-2      sessioninfo_1.2.3
[16] pkgbuild_1.4.6    urlchecker_1.0.1  promises_1.3.2    purrr_1.0.4       httr2_1.1.1      
[21] shiny_1.10.0      cli_3.6.4         rlang_1.1.5       crayon_1.5.3      ellipsis_0.3.2   
[26] remotes_2.5.0     withr_3.0.2       cachem_1.1.0      devtools_2.4.5    tools_4.4.3      
[31] tzdb_0.4.0        memoise_2.0.1     httpuv_1.6.15     curl_6.2.2        mime_0.12        
[36] vctrs_0.6.5       R6_2.6.1          png_0.1-8         lifecycle_1.0.4   lubridate_1.9.4  
[41] snakecase_0.11.1  htmlwidgets_1.6.4 fs_1.6.5          usethis_3.1.0     miniUI_0.1.1.1   
[46] janitor_2.2.1     pkgconfig_2.0.3   later_1.4.1       rJava_1.0-11      pillar_1.10.1    
[51] profvis_0.4.0     glue_1.8.0        Rcpp_1.0.14       tibble_3.2.1      tidyselect_1.2.1 
[56] rstudioapi_0.17.1 xtable_1.8-4      htmltools_0.5.8.1 readr_2.1.5       compiler_4.4.3   

It looks like every load_results() for 2025 is failing. Using other years seems to work fine.
Regards
Ab

**Comment by appiehappie999** [comment]
I can confirm that with load_results(2025,1) gives an error. It works fine for all the races of last year

Regards
Ab

**Comment by pbulsink** [comment]
GitHub version should work now - you can install the development version of this package using the following code:

`devtools::install_github("SCasanova/f1dataR")`

We'll push this to CRAN in the coming days. Thanks for your report!!

**Comment by pbulsink** [comment]
Cran should be showing version 2.0.1 with the fix included.

**Comment by appiehappie999** [comment]
Thanks for the update. I’ll check CRAN. I’ve updated my computer with the new version, but found still an issue.

I’ve tried the following code:

library(f1dataR)
py_require()

use_python("/Users/abdehaas/.pyenv/shims/python3")
change_cache(cache = "/Users/abdehaas/documents/f1cache", create_dir = FALSE, persist = TRUE)


thisYear      <- get_current_season() # info available from 2018
first       <- load_results(season = thisYear,1)
second      <- load_results(2025,round = 2)
# third1      <- load_results(2025,3)                    <- error on the first run
third2      <- load_results(2025,"last”)             
third3      <- load_results(2025,round = "last")


Result of executions:
# > source("~/.active-rstudio-document")
# Error in UseMethod("unnest") : 
#   no applicable method for 'unnest' applied to an object of class “NULL"


# > source("~/.active-rstudio-document")

**Comment by appiehappie999** [comment]
In addition the data for 2025 round 1 is not complete; all the top_speed values are NA. The same applies for the others

Example load_result(2025,2)

￼

I’ve  been a stronger user of the ergast database and have extended my own database with additional information; so I the near future I’ll test quite a bit of your functions.

Regards
Ab

**Comment by pbulsink** [comment]
Hi Ab, this is an issue with the upstream data supply. We don't calculate those items, just present what's available in the API.

There may be a discussion about this at the github.com/jolpica/jolpica-f1 repo, or you could start one there if it doesn't yet exist.
